### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by dodoaska** [fredriknk/pykey#1]
i dont understand how yto use .
1 need me find a bitcoin address , and copy the photo?

**Comment by fredriknk** [comment]
Do you have Python 3.8 installed, and the required libraries?

**Comment by fredriknk** [comment]
To use it, you will need to install python 3.8, and you need the following libraries:
hashlib, binascii, requests, os and sys

If you download python from a distribution like Anaconda, 

See guide:
https://problemsolvingwithpython.com/01-Orientation/01.03-Installing-Anaconda-on-Windows/

you will get most of them included (except hashlib and binascii) . The rest you will have you will have to install them with Conda.

Guide:
https://docs.anaconda.com/anaconda/user-guide/tasks/install-packages/

After you have done all that, you will need to create an uncompressed image of the harddrive where you think the bitcoin wallet is located.

when all this is done you can run the python script by starting it in the terminal like this:

python pykey.py ./filenameofiso.img

where filenameofiso is the filename of your iso file.

**Comment by dodoaska** [comment]
I use KALI

I will install anaconda on Kali

**Comment by fredriknk** [comment]
Ah, if you use a default install of Kali you very likely have python installed allready

Have you tried to cd to the folder where you cloned the repo, and run:

python pykey.py ./testfile2(wallet).img

?

You might need to run it as:
python3 pykey.py ./testfile2(wallet).img
